version: '3.8'

networks:
  kafka-network:
    name: kafka-network

volumes: 
  mongo-volume:

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - kafka-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - 9092:9092
    networks:
      - kafka-network
    environment:
      KAFKA_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://kafka:9092,INSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,INSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: OUTSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    depends_on:
      - zookeeper
  mongodb:
    image: 'mongo'
    ports:
      - 27017:27017
    networks:
      - kafka-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ontime
    volumes: 
        - mongo-volume:/data/db
  
  spring-kafka:
    image: 'spring-kafka:latest'
    ports:
      - 8080:8080
    networks:
      - kafka-network
    environment:
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - zookeeper
      - kafka
  
  spring-mongo:
    image: 'spring-mongo:latest'
    ports:
      - 8081:8081
    networks:
      - kafka-network
    environment: 
      - MONGO_HOST=mongodb
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
    depends_on:
      - zookeeper
      - kafka
      - mongodb