server:
  port: ${SERVER_PORT:8081}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      authentication-database: ${MONGO_AUTH_DB:admin}
      database: ${MONGO_DB_NAME:akademik}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:ontime}

  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          autoCreateTopics: true
          brokers:
            - ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

      bindings:
        input:
          binder: kafka
          destination: ${TOPIC_NAME:test}
          content-type: application/json
          group: ${KAFKA_GROUP:data-mongo}